//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTracker_ProjectDLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllRoleDetail
    {
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string RoleName { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CompanyName { get; set; }
    }
}
