//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTracker_ProjectDLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendenceDetail
    {
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int DepartmentId { get; set; }
        public int DesignationId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> TotalSecond { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
