//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTracker_ProjectDLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAssign
    {
        public int ProjectAssignId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> WeeklyLimit { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> EntryUser { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual CompanyMaster CompanyMaster { get; set; }
        public virtual ProjectMaster ProjectMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
