//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTracker_ProjectDLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenShot
    {
        public int ScreenShotId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> ScreenShotTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual CompanyMaster CompanyMaster { get; set; }
        public virtual ProjectMaster ProjectMaster { get; set; }
        public virtual TaskMaster TaskMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
